---
- hosts: all
  become: true

  roles:
    - role: jgeusebroek.java

  pre_tasks:
  - name: Create man directory, not available in Docker images
    file:
      path: /usr/share/man/man1
      state: directory